// Weekly portfolio digest — self-contained HTML (inline styles, table layout)
// suitable for email. A future cron job sends this via Resend/Postmark; today
// it can be previewed at /api/digest.

import { getKpis, getInsights, getArrears } from "./queries";
import type { Locale } from "./enums";

function eur(v: number): string {
  return new Intl.NumberFormat("nl-NL", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(v);
}

export async function buildDigestHtml(locale: Locale = "nl"): Promise<string> {
  const [kpis, insights, arrears] = await Promise.all([getKpis(), getInsights(), getArrears()]);
  const nl = locale === "nl";

  const kpiRows: [string, string][] = [
    [nl ? "Totale waarde (WOZ)" : "Total value (WOZ)", eur(kpis.totalValue)],
    [nl ? "Maandelijkse huur" : "Monthly rent", eur(kpis.monthlyIncome)],
    [nl ? "Netto cashflow / mnd" : "Net cashflow / mo", eur(kpis.netCashflow)],
    [nl ? "Openstaande achterstand" : "Outstanding arrears", eur(kpis.totalArrears)],
    [nl ? "Bezettingsgraad" : "Occupancy", `${Math.round(kpis.occupancy)}%`],
    [nl ? "Open meldingen" : "Open issues", String(kpis.openIssues)],
  ];

  const section = (title: string, items: string[]) =>
    items.length === 0
      ? ""
      : `<h3 style="margin:18px 0 6px;font-size:14px;color:#0f172a">${title} (${items.length})</h3>
         <ul style="margin:0;padding-left:18px;color:#334155;font-size:13px;line-height:1.6">
           ${items.slice(0, 8).map((i) => `<li>${i}</li>`).join("")}
           ${items.length > 8 ? `<li style="color:#94a3b8">… +${items.length - 8}</li>` : ""}
         </ul>`;

  const topArrears = arrears.slice(0, 8).map((a) => `<b>${a.tenant}</b> — ${a.propertyName} · ${a.periodYm} · ${eur(a.outstanding)} (${a.daysLate} ${nl ? "dgn" : "days"})`);
  const vacant = insights.vacant.map((v) => `<b>${v.title}</b> — ${v.detail}`);
  const expiring = insights.expiring.map((e) => `<b>${e.title}</b> — ${e.detail}${e.date ? ` · ${e.date.toLocaleDateString("nl-NL")}` : ""}`);
  const indexation = insights.indexation.map((i) => `<b>${i.title}</b> — ${i.detail}`);

  return `<!doctype html><html><body style="margin:0;padding:24px;background:#f8fafc;font-family:system-ui,Segoe UI,Roboto,sans-serif">
  <div style="max-width:640px;margin:0 auto;background:#ffffff;border:1px solid #e2e8f0;border-radius:12px;padding:24px">
    <div style="font-size:18px;font-weight:700;color:#0f172a">StrateX — ${nl ? "Wekelijkse portefeuille-update" : "Weekly portfolio update"}</div>
    <div style="font-size:12px;color:#94a3b8;margin-bottom:16px">${new Date().toLocaleDateString(nl ? "nl-NL" : "en-GB", { dateStyle: "long" })} · ${kpis.propertyCount} ${nl ? "panden" : "properties"}</div>
    <table style="width:100%;border-collapse:collapse">
      ${kpiRows.map(([k, v]) => `<tr>
        <td style="padding:6px 0;font-size:13px;color:#64748b;border-bottom:1px solid #f1f5f9">${k}</td>
        <td style="padding:6px 0;font-size:13px;font-weight:600;color:#0f172a;text-align:right;border-bottom:1px solid #f1f5f9">${v}</td>
      </tr>`).join("")}
    </table>
    ${section(nl ? "⚠ Achterstanden" : "⚠ Arrears", topArrears)}
    ${section(nl ? "🏚 Leegstand" : "🏚 Vacancy", vacant)}
    ${section(nl ? "⏳ Aflopende contracten" : "⏳ Expiring leases", expiring)}
    ${section(nl ? "📈 Indexatie mogelijk" : "📈 Indexation available", indexation)}
    <div style="margin-top:20px;font-size:11px;color:#94a3b8">${nl ? "Automatisch gegenereerd door StrateX." : "Automatically generated by StrateX."}</div>
  </div>
</body></html>`;
}
